apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: service-dns-update
  name: service-dns-update
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-dns-update
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-dns-update
      name: service-dns-update
    spec:
      containers:
      - image: 307424997672.dkr.ecr.us-east-1.amazonaws.com/service-dns-update:v1.4.0
        imagePullPolicy: Always
        name: app
        # args:
        # - -sync-interval=60
        # - -namespace=staging
        # - -dry-run=false
